### ISSUE TITLE
Option to specify the top level heading

### ISSUE THREAD

**Issue by scottmartin** [remarkjs/remark-normalize-headings#2]
How hard would it be to provide an option to set the top level heading? I'm going to be using this for a blog, and since level 1 will be used for the post's title I'd like level 2 to be the highest used in the markdown. That way, even if someone used a level 1 it would get lowered to a level 2, and so on.

**Comment by wooorm** [comment]
Sure, doable, interested in doing a PR?

**Comment by scottmartin** [comment]
I don't have time right now, but I will look into it this weekend. I'm guessing it would be on the mdast-normalize-headings project first. Right?

**Comment by wooorm** [comment]
Yup!

**Comment by scottmartin** [comment]
I got a chance to look over the code and I realized that what I want may be better served by just making a new remark plugin rather than complicate your code unnecessarily. In the end, I don't really need the normalization. I just need to bump all the headers by a minimum level.

If I do publish the plugin I'll probably base it on your work and link back to your project.
